Implement basic map view
Expensify/react-native-x-maps pull request #16
Opened 2023-08-04 21:10 UTC by hayata-suenaga

### Details

### Related Issues

GH_LINK

### Manual Tests

### Linked PRs

2023-08-11 19:29 UTC, thienlnam requested changes
Looks good, can’t speak much to the Mapbox stuff but left some comments regarding keeping conventions same as App styling

2023-08-11 19:29 UTC, thienlnam commented on .eslintrc.js
> +        'no-use-before-define': 'off',
Are these the same ones in App?

2023-08-11 19:29 UTC, thienlnam commented on src/MapView/consts.ts
> +import {MapViewProps} from './MapViewTypes';
To be consistent, lets rename this file to CONST?

2023-08-11 19:29 UTC, thienlnam commented on src/MapView/utils.ts
> +export const getBounds = (waypoints: Array<[number, number]>): {southWest: [number, number]; northEast: [number, number]} => {
Let’s try to keep the style consistent as the App repo - so making this a function

and then export default {
Function
}

2023-08-11 19:43 UTC, hayata-suenaga commented on .eslintrc.js
> +        'no-use-before-define': 'off',
np 😅 turning it back one

2023-08-11 21:57 UTC, thienlnam approved these changes

2023-08-11 21:57 UTC, merged

2023-09-17 20:37 UTC, allroundexperts commented on src/MapView/MapView.tsx
> +    }, []);
This code caused https://github.com/Expensify/App/issues/25732. Map box API doesn't seem to support `flyTo` well enough on native platforms.

2023-09-18 00:07 UTC, hayata-suenaga commented on src/MapView/MapView.tsx
> +    }, []);
it's rather the issue with the libraries themself than a regression but yea we should have tested this thoroughly